describe('security', () => {
    it('security', () => {

      const password = Cypress.env('password')

      cy.visit('https://wordpress.com/log-in?redirect_to=%2Fme%2Fsecurity');
      cy.get('#usernameOrEmail').type('rhefele@gmail.com');
      cy.get('.form-button').click();
      cy.get('form').submit();

      cy.get('[name=password]')
      cy.get('#password').type(password);
      cy.get('.form-button').click();
      cy.get('form').submit();
      cy.url().should('contains', 'https://wordpress.com/me/security');

      cy.contains('Security').should('have.text', 'Security')
      
      //Yes, the space is needed if checking the entire string
      cy.contains('You\'ve recently used this password. Try something new.').should('have.text',' You\'ve recently used this password. Try something new.')

      
      //Nav to Social Login - This is being presented in 2 ways. Tabs and dropdown selection.
      //The easiest way was to use visit
      cy.visit('https://wordpress.com/me/security/social-login');
      cy.contains('You’ll be able to log in faster by linking your WordPress.com account with the following third-party services. We’ll never post without your permission.')
        .should('have.text','You’ll be able to log in faster by linking your WordPress.com account with the following third-party services. We’ll never post without your permission.')

      ////Nav to Two-Step Authentication
      cy.visit('https://wordpress.com/me/security/two-step');
      cy.contains('Two-Step Authentication adds an extra layer of security to your account. Once enabled, logging in to WordPress.com will require you to enter a unique passcode generated by an app on your mobile device or sent via text message, in addition to your username and password.')
        .should('have.text','Two-Step Authentication adds an extra layer of security to your account. Once enabled, logging in to WordPress.com will require you to enter a unique passcode generated by an app on your mobile device or sent via text message, in addition to your username and password.')

      //Toggle on Set up using SMS
      cy.get('#sms-auth').click();
      //Toggle on Set up using an app
      cy.get('#app-auth').click();
      
      cy.visit('https://wordpress.com/me/security/connected-applications');
      cy.contains('Gravatar').click()
      cy.contains('Application website').should('have.text','Application website')
      cy.get('#primary > main > div.card.foldable-card.connected-application-item.is-expanded.has-expanded-summary.is-compact > div.foldable-card__content > div > h2:nth-child(3)')
        .should('have.text','Authorized on')  
      
      cy.get('#primary > main > div.card.foldable-card.connected-application-item.is-expanded.has-expanded-summary.is-compact > div.foldable-card__content > div > div > div > h2')
        .should('have.text','Access scopeAuthentication')

      cy.get('#primary > main > div.card.foldable-card.connected-application-item.is-expanded.has-expanded-summary.is-compact > div.foldable-card__content > div > h2:nth-child(6)')
        .should('have.text','Access permissions')

      //logout
      //validate logout home
      cy.contains('Log out').click()
      cy.url().should('include', 'https://wordpress.com/?apppromo')     
    
    })
  })

  
